stages:
  - build

variables:
  BUILDX_VERSION: "0.11.2"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  REGISTRY: quay.io
  REPOSITORY: ""
  IMAGE_NAME: ${REGISTRY}/${REPOSITORY}/automotive-dev-operator
  VERSION: "${CI_COMMIT_SHORT_SHA}"

build-operator-arm64:
  tags:
    - saas-linux-small-arm64
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-arm64  # Note: Using arm64 version
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - docker buildx create --name multiarch-builder --driver docker-container --use
    - docker buildx inspect --bootstrap
    - echo "${REGISTRY_PASSWORD}" | docker login ${REGISTRY} -u "${REGISTRY_USER}" --password-stdin
  script:
    - docker buildx build --platform linux/arm64
      --push
      -t "${IMAGE_NAME}:${VERSION}-arm64"
      -t "${IMAGE_NAME}:latest-arm64" .
  only:
    - main
    - tags

# build-operator-amd64:
#   tags:
#     - saas-linux-small-amd64
#   stage: build
#   image: docker:24.0.5
#   services:
#     - docker:24.0.5-dind
#   before_script:
#     - mkdir -p ~/.docker/cli-plugins
#     - wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64  # Note: Using amd64 version
#     - chmod +x ~/.docker/cli-plugins/docker-buildx
#     - docker buildx create --name multiarch-builder --driver docker-container --use
#     - docker buildx inspect --bootstrap
#     - echo "${REGISTRY_PASSWORD}" | docker login ${REGISTRY} -u "${REGISTRY_USER}" --password-stdin
#   script:
#     - docker buildx build --platform linux/amd64
#       --push
#       -t "${IMAGE_NAME}:${VERSION}-amd64"
#       -t "${IMAGE_NAME}:latest-amd64" .
#   only:
#     - main
#     - tags
