stages:
  - build
  - release

variables:
  BUILDX_VERSION: "0.11.2"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  REGISTRY: quay.io
  REPOSITORY: ""
  OPERATOR_IMAGE: ${REGISTRY}/${REPOSITORY}/automotive-dev-operator
  AIB_BASE_IMAGE: ${REGISTRY}/${REPOSITORY}/aib-base-dev
  VERSION: "${CI_COMMIT_SHORT_SHA}"
  AIB_CLI_BINARY: "aib-cli"

build-aib-cli:
  tags:
    - saas-linux-small-arm64
  stage: build
  image: golang:1.23-alpine
  script:
    - apk add --no-cache make git bash
    - mkdir -p ./bin
    - make build-cli
    - cp bin/aib-cli ${AIB_CLI_BINARY}-${VERSION}-arm64
  artifacts:
    paths:
      - ${AIB_CLI_BINARY}-${VERSION}-arm64
    expire_in: 1 week
  only:
    - main
    - tags

create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - build-aib-cli
  script:
    - echo "Creating release for version ${VERSION}"
  release:
    name: "Release ${VERSION}"
    description: "Automotive Image Builder CLI ${VERSION}"
    tag_name: "${VERSION}"
    ref: "${CI_COMMIT_SHA}"
    assets:
      links:
        - name: "${AIB_CLI_BINARY}-arm64"
          url: "${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_REF_NAME}/raw/${AIB_CLI_BINARY}-${VERSION}-arm64?job=build-aib-cli"
          link_type: "package"
  only:
    - tags
