stages:
  - build

variables:
  BUILDX_VERSION: "0.11.2"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  REGISTRY: quay.io
  IMAGE_NAME: ${REGISTRY}/your-namespace/automotive-dev-operator
  VERSION: "${CI_COMMIT_SHORT_SHA}"

build-operator:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - docker buildx create --name multiarch-builder --driver docker-container --use
    - docker buildx inspect --bootstrap
    - echo "${REGISTRY_PASSWORD}" | docker login ${REGISTRY} -u "${REGISTRY_USER}" --password-stdin
  script:
    - docker buildx build --platform linux/amd64,linux/arm64
      --push
      -t ${IMAGE_NAME}:${VERSION}
      -t ${IMAGE_NAME}:latest .
  only:
    - main
    - tags
