---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automotive.sdv.cloud.redhat.com
  resources:
  - imagebuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automotive.sdv.cloud.redhat.com
  resources:
  - imagebuilds/finalizers
  verbs:
  - update
- apiGroups:
  - automotive.sdv.cloud.redhat.com
  resources:
  - imagebuilds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - use
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints/finalizers
  verbs:
  - update
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelines
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
