---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - automotive.sdv.cloud.redhat.com
  resources:
  - imagebuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automotive.sdv.cloud.redhat.com
  resources:
  - imagebuilds/finalizers
  verbs:
  - update
- apiGroups:
  - automotive.sdv.cloud.redhat.com
  resources:
  - imagebuilds/status
  verbs:
  - get
  - patch
  - update
