apiVersion: automotive.sdv.cloud.redhat.com/v1
kind: ImageBuild
metadata:
  labels:
    app.kubernetes.io/name: automotive-dev-operator
    app.kubernetes.io/managed-by: kustomize
  name: imagebuild-sample
spec:
  # TODO(user): Add fields here
